### ISSUE TITLE
Moodle - Undefined property: stdClass::$introformat

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/webwork.maa.org#7]
https://test1.webwork.maa.org/moodle/mod/data/index.php?id=3
```
Databases

Notice: Undefined property: stdClass::$introformat in
/var/www/html/moodle/mod/data/index.php on line 133
```

---
https://test1.webwork.maa.org/moodle/mod/data/view.php?d=2&advanced=0&paging&page=1

```
Notice: Undefined property: stdClass::$introformat in /var/www/html/moodle/lib/weblib.php on line 1595
```

```

**Comment by mgage** [comment]
Coding error -- probably related to the reformatting needed for introformat in the database.

**Comment by mgage** [comment]
This also give the error:
https://test1.webwork.maa.org/moodle/course/view.php?id=5

**Comment by nadavkav** [comment]
Every textarea field in Moodle as a related introformat field to help internal validation and display filtering function work properly, and of course... enable a different type of textarea editor to the users.
It seems, the upgrade process missed fixing it in the schema. and you should probably modify it manually in the db table mdl_data, see:
https://github.com/moodle/moodle/blob/master/mod/data/db/install.xml#L13

**Comment by nadavkav** [comment]
Also, maybe: https://tracker.moodle.org/browse/MDL-23204

**Comment by nadavkav** [comment]
Also interesting: https://tracker.moodle.org/browse/MDL-49101

**Comment by mgage** [comment]
I did fix this.  The $introformat problem was solved (hacked) manually as you describe.  And the hacks that I did to the schema worked pretty well for the forums attached to  UsingWW.  The forums that are not working so well are the older ones which were attached to the AIM course from 2007.  I hadn’t created that course
before I did the original import of the database and while all of the contents of the posts uploaded fine, the links between posts and discussions got 
messed up and I haven’t been able to hack a fix.  

Starting fresh and upgrading step by step is the sensible thing to do at this point.   It requires switching php simultaneously since moodle 1.9 only runs on php 5
and moodle 3.8 only runs on php 7 (sigh).  Serves us right for not updating moodle constantly (if it’s not broke don’t fix it. :-(  )

Thanks for your help.

Take care,

Mike

**Comment by nadavkav** [comment]
I completely forgot about the PHP version "challenges" :-(

Anyways, It looks like you are on the right track with this :-)
If you get into any more challenges, please let me know.

Best,
Nadav

**Comment by mgage** [comment]
Thanks.  I appreciate having someone else to talk to or to at least have an additional eye on the problem when I get stuck.

I’ll keep you informed.  The most essential information is preserved if awkward to get at sometimes. There is now less urgency  but I will try again to see if I can make 
the transferred forum work seamlessly.

Take care,

Mike

**Comment by mgage** [comment]
Fixed by reimporting the database and upgrading one step at a time from moodle 1.9 to 3.8
